# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import img_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(418, 478)
        MainWindow.setFocusPolicy(Qt.NoFocus)
        MainWindow.setContextMenuPolicy(Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u":/icon/favicon.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.verticalSlider = QSlider(MainWindow)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(55, 20, 22, 84))
        self.verticalSlider.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider.setMaximum(99)
        self.verticalSlider.setSingleStep(1)
        self.verticalSlider.setValue(50)
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.horizontalSlider = QSlider(MainWindow)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(26, 110, 84, 22))
        self.horizontalSlider.setLayoutDirection(Qt.RightToLeft)
        self.horizontalSlider.setValue(50)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.label = QLabel(MainWindow)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(32, 125, 71, 41))
        self.label.setBaseSize(QSize(200, 200))
        font = QFont()
        font.setFamily(u"Bahnschrift")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setFrameShadow(QFrame.Sunken)
        self.label.setTextFormat(Qt.PlainText)
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(MainWindow)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 421, 481))
        self.label_4.setPixmap(QPixmap(u":/face/face.jpg"))
        self.label_4.setScaledContents(True)
        self.verticalSlider_2 = QSlider(MainWindow)
        self.verticalSlider_2.setObjectName(u"verticalSlider_2")
        self.verticalSlider_2.setGeometry(QRect(203, 19, 22, 84))
        self.verticalSlider_2.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_2.setMaximum(99)
        self.verticalSlider_2.setSingleStep(1)
        self.verticalSlider_2.setValue(50)
        self.verticalSlider_2.setOrientation(Qt.Vertical)
        self.label_2 = QLabel(MainWindow)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(180, 127, 71, 41))
        self.label_2.setBaseSize(QSize(200, 200))
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QFrame.NoFrame)
        self.label_2.setFrameShadow(QFrame.Sunken)
        self.label_2.setTextFormat(Qt.PlainText)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.horizontalSlider_2 = QSlider(MainWindow)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setGeometry(QRect(174, 109, 84, 22))
        self.horizontalSlider_2.setLayoutDirection(Qt.RightToLeft)
        self.horizontalSlider_2.setValue(50)
        self.horizontalSlider_2.setTracking(True)
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)
        self.horizontalSlider_2.setInvertedAppearance(False)
        self.horizontalSlider_2.setInvertedControls(False)
        self.verticalSlider_3 = QSlider(MainWindow)
        self.verticalSlider_3.setObjectName(u"verticalSlider_3")
        self.verticalSlider_3.setGeometry(QRect(339, 19, 22, 84))
        self.verticalSlider_3.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_3.setMaximum(99)
        self.verticalSlider_3.setSingleStep(1)
        self.verticalSlider_3.setValue(50)
        self.verticalSlider_3.setOrientation(Qt.Vertical)
        self.label_3 = QLabel(MainWindow)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(316, 124, 71, 41))
        self.label_3.setBaseSize(QSize(200, 200))
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_3.setFrameShape(QFrame.NoFrame)
        self.label_3.setFrameShadow(QFrame.Sunken)
        self.label_3.setTextFormat(Qt.PlainText)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.horizontalSlider_3 = QSlider(MainWindow)
        self.horizontalSlider_3.setObjectName(u"horizontalSlider_3")
        self.horizontalSlider_3.setGeometry(QRect(310, 109, 84, 22))
        self.horizontalSlider_3.setLayoutDirection(Qt.RightToLeft)
        self.horizontalSlider_3.setValue(50)
        self.horizontalSlider_3.setTracking(True)
        self.horizontalSlider_3.setOrientation(Qt.Horizontal)
        self.horizontalSlider_3.setInvertedAppearance(False)
        self.horizontalSlider_3.setInvertedControls(False)
        self.verticalSlider_5 = QSlider(MainWindow)
        self.verticalSlider_5.setObjectName(u"verticalSlider_5")
        self.verticalSlider_5.setGeometry(QRect(60, 190, 22, 84))
        self.verticalSlider_5.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_5.setMaximum(99)
        self.verticalSlider_5.setSingleStep(1)
        self.verticalSlider_5.setValue(50)
        self.verticalSlider_5.setOrientation(Qt.Vertical)
        self.verticalSlider_4 = QSlider(MainWindow)
        self.verticalSlider_4.setObjectName(u"verticalSlider_4")
        self.verticalSlider_4.setGeometry(QRect(20, 190, 22, 84))
        self.verticalSlider_4.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_4.setMaximum(99)
        self.verticalSlider_4.setSingleStep(1)
        self.verticalSlider_4.setValue(50)
        self.verticalSlider_4.setOrientation(Qt.Vertical)
        self.verticalSlider_6 = QSlider(MainWindow)
        self.verticalSlider_6.setObjectName(u"verticalSlider_6")
        self.verticalSlider_6.setGeometry(QRect(386, 190, 22, 84))
        self.verticalSlider_6.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_6.setMaximum(99)
        self.verticalSlider_6.setSingleStep(1)
        self.verticalSlider_6.setValue(50)
        self.verticalSlider_6.setOrientation(Qt.Vertical)
        self.verticalSlider_7 = QSlider(MainWindow)
        self.verticalSlider_7.setObjectName(u"verticalSlider_7")
        self.verticalSlider_7.setGeometry(QRect(346, 190, 22, 84))
        self.verticalSlider_7.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_7.setMaximum(99)
        self.verticalSlider_7.setSingleStep(1)
        self.verticalSlider_7.setValue(50)
        self.verticalSlider_7.setOrientation(Qt.Vertical)
        self.verticalSlider_8 = QSlider(MainWindow)
        self.verticalSlider_8.setObjectName(u"verticalSlider_8")
        self.verticalSlider_8.setGeometry(QRect(343, 320, 22, 84))
        self.verticalSlider_8.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_8.setMaximum(99)
        self.verticalSlider_8.setSingleStep(1)
        self.verticalSlider_8.setValue(50)
        self.verticalSlider_8.setOrientation(Qt.Vertical)
        self.label_5 = QLabel(MainWindow)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(273, 425, 141, 41))
        self.label_5.setBaseSize(QSize(200, 200))
        font1 = QFont()
        font1.setFamily(u"Bahnschrift")
        font1.setPointSize(14)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setWeight(50)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        self.label_5.setFont(font1)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5.setFrameShape(QFrame.NoFrame)
        self.label_5.setFrameShadow(QFrame.Sunken)
        self.label_5.setTextFormat(Qt.PlainText)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.horizontalSlider_4 = QSlider(MainWindow)
        self.horizontalSlider_4.setObjectName(u"horizontalSlider_4")
        self.horizontalSlider_4.setGeometry(QRect(314, 410, 84, 22))
        self.horizontalSlider_4.setLayoutDirection(Qt.RightToLeft)
        self.horizontalSlider_4.setValue(50)
        self.horizontalSlider_4.setTracking(True)
        self.horizontalSlider_4.setOrientation(Qt.Horizontal)
        self.horizontalSlider_4.setInvertedAppearance(False)
        self.horizontalSlider_4.setInvertedControls(False)
        self.verticalSlider_9 = QSlider(MainWindow)
        self.verticalSlider_9.setObjectName(u"verticalSlider_9")
        self.verticalSlider_9.setGeometry(QRect(199, 322, 22, 84))
        self.verticalSlider_9.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_9.setMaximum(99)
        self.verticalSlider_9.setSingleStep(1)
        self.verticalSlider_9.setValue(50)
        self.verticalSlider_9.setOrientation(Qt.Vertical)
        self.label_6 = QLabel(MainWindow)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(146, 427, 141, 41))
        self.label_6.setBaseSize(QSize(200, 200))
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_6.setFrameShape(QFrame.NoFrame)
        self.label_6.setFrameShadow(QFrame.Sunken)
        self.label_6.setTextFormat(Qt.PlainText)
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.horizontalSlider_5 = QSlider(MainWindow)
        self.horizontalSlider_5.setObjectName(u"horizontalSlider_5")
        self.horizontalSlider_5.setGeometry(QRect(170, 412, 84, 22))
        self.horizontalSlider_5.setLayoutDirection(Qt.RightToLeft)
        self.horizontalSlider_5.setValue(50)
        self.horizontalSlider_5.setTracking(True)
        self.horizontalSlider_5.setOrientation(Qt.Horizontal)
        self.horizontalSlider_5.setInvertedAppearance(False)
        self.horizontalSlider_5.setInvertedControls(False)
        self.horizontalSlider_6 = QSlider(MainWindow)
        self.horizontalSlider_6.setObjectName(u"horizontalSlider_6")
        self.horizontalSlider_6.setGeometry(QRect(31, 410, 84, 22))
        self.horizontalSlider_6.setLayoutDirection(Qt.RightToLeft)
        self.horizontalSlider_6.setValue(50)
        self.horizontalSlider_6.setTracking(True)
        self.horizontalSlider_6.setOrientation(Qt.Horizontal)
        self.horizontalSlider_6.setInvertedAppearance(False)
        self.horizontalSlider_6.setInvertedControls(False)
        self.label_7 = QLabel(MainWindow)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(7, 425, 131, 41))
        self.label_7.setBaseSize(QSize(200, 200))
        self.label_7.setFont(font1)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_7.setFrameShape(QFrame.NoFrame)
        self.label_7.setFrameShadow(QFrame.Sunken)
        self.label_7.setTextFormat(Qt.PlainText)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.verticalSlider_10 = QSlider(MainWindow)
        self.verticalSlider_10.setObjectName(u"verticalSlider_10")
        self.verticalSlider_10.setGeometry(QRect(60, 320, 22, 84))
        self.verticalSlider_10.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_10.setMaximum(99)
        self.verticalSlider_10.setSingleStep(1)
        self.verticalSlider_10.setValue(50)
        self.verticalSlider_10.setOrientation(Qt.Vertical)
        self.label_8 = QLabel(MainWindow)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 280, 41, 41))
        self.label_8.setBaseSize(QSize(200, 200))
        font2 = QFont()
        font2.setFamily(u"Bahnschrift")
        font2.setPointSize(12)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setWeight(50)
        font2.setStrikeOut(False)
        font2.setKerning(True)
        self.label_8.setFont(font2)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8.setFrameShape(QFrame.NoFrame)
        self.label_8.setFrameShadow(QFrame.Sunken)
        self.label_8.setTextFormat(Qt.PlainText)
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(MainWindow)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(54, 280, 41, 41))
        self.label_9.setBaseSize(QSize(200, 200))
        self.label_9.setFont(font2)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_9.setFrameShape(QFrame.NoFrame)
        self.label_9.setFrameShadow(QFrame.Sunken)
        self.label_9.setTextFormat(Qt.PlainText)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(MainWindow)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(335, 279, 41, 41))
        self.label_10.setBaseSize(QSize(200, 200))
        self.label_10.setFont(font2)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_10.setFrameShape(QFrame.NoFrame)
        self.label_10.setFrameShadow(QFrame.Sunken)
        self.label_10.setTextFormat(Qt.PlainText)
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(MainWindow)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(376, 279, 41, 41))
        self.label_11.setBaseSize(QSize(200, 200))
        self.label_11.setFont(font2)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11.setFrameShape(QFrame.NoFrame)
        self.label_11.setFrameShadow(QFrame.Sunken)
        self.label_11.setTextFormat(Qt.PlainText)
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.verticalSlider_12 = QSlider(MainWindow)
        self.verticalSlider_12.setObjectName(u"verticalSlider_12")
        self.verticalSlider_12.setGeometry(QRect(202, 210, 22, 84))
        self.verticalSlider_12.setLayoutDirection(Qt.LeftToRight)
        self.verticalSlider_12.setMaximum(99)
        self.verticalSlider_12.setSingleStep(1)
        self.verticalSlider_12.setValue(50)
        self.verticalSlider_12.setOrientation(Qt.Vertical)
        self.horizontalSlider_7 = QSlider(MainWindow)
        self.horizontalSlider_7.setObjectName(u"horizontalSlider_7")
        self.horizontalSlider_7.setGeometry(QRect(172, 240, 84, 22))
        self.horizontalSlider_7.setLayoutDirection(Qt.RightToLeft)
        self.horizontalSlider_7.setValue(50)
        self.horizontalSlider_7.setTracking(True)
        self.horizontalSlider_7.setOrientation(Qt.Horizontal)
        self.horizontalSlider_7.setInvertedAppearance(False)
        self.horizontalSlider_7.setInvertedControls(False)
        self.pushButton = QPushButton(MainWindow)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QRect(19, 50, 21, 21))
        font3 = QFont()
        font3.setKerning(False)
        self.pushButton.setFont(font3)
        self.pushButton.setMouseTracking(True)
        self.pushButton.setTabletTracking(True)
#if QT_CONFIG(tooltip)
        self.pushButton.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton.setLayoutDirection(Qt.LeftToRight)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        icon1 = QIcon()
        icon1.addFile(u":/icon_yelloo/icon_yelloo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton_2 = QPushButton(MainWindow)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(170, 50, 21, 21))
        self.pushButton_2.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_2.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_2.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_2.setText(u"")
        self.pushButton_2.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_2.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_3 = QPushButton(MainWindow)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QRect(370, 50, 21, 21))
        self.pushButton_3.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_3.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_3.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_3.setText(u"")
        self.pushButton_3.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_3.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setFlat(True)
        self.pushButton_4 = QPushButton(MainWindow)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QRect(22, 170, 21, 21))
        self.pushButton_4.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_4.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_4.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_4.setText(u"")
        self.pushButton_4.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_4.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_5 = QPushButton(MainWindow)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QRect(62, 170, 21, 21))
        self.pushButton_5.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_5.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_5.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_5.setText(u"")
        self.pushButton_5.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_5.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setFlat(True)
        self.pushButton_6 = QPushButton(MainWindow)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QRect(348, 170, 21, 21))
        self.pushButton_6.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_6.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_6.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_6.setText(u"")
        self.pushButton_6.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_6.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setFlat(True)
        self.pushButton_7 = QPushButton(MainWindow)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QRect(388, 170, 21, 21))
        self.pushButton_7.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_7.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_7.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_7.setText(u"")
        self.pushButton_7.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_7.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setFlat(True)
        self.pushButton_8 = QPushButton(MainWindow)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setGeometry(QRect(20, 350, 21, 21))
        self.pushButton_8.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_8.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_8.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_8.setText(u"")
        self.pushButton_8.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_8.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_8.setCheckable(False)
        self.pushButton_8.setAutoDefault(False)
        self.pushButton_8.setFlat(True)
        self.pushButton_9 = QPushButton(MainWindow)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setGeometry(QRect(380, 350, 21, 21))
        self.pushButton_9.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_9.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_9.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_9.setText(u"")
        self.pushButton_9.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_9.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setAutoDefault(False)
        self.pushButton_9.setFlat(True)
        self.pushButton_10 = QPushButton(MainWindow)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setGeometry(QRect(160, 350, 21, 21))
        self.pushButton_10.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_10.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_10.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_10.setText(u"")
        self.pushButton_10.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_10.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_10.setCheckable(False)
        self.pushButton_10.setAutoDefault(False)
        self.pushButton_10.setFlat(True)
        self.pushButton_11 = QPushButton(MainWindow)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setGeometry(QRect(151, 270, 21, 21))
        self.pushButton_11.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_11.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_11.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_11.setAutoFillBackground(False)
        self.pushButton_11.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_11.setText(u"")
        self.pushButton_11.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_11.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_11.setCheckable(False)
        self.pushButton_11.setAutoDefault(False)
        self.pushButton_11.setFlat(True)
        self.pushButton_12 = QPushButton(MainWindow)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setEnabled(True)
        self.pushButton_12.setGeometry(QRect(90, 50, 21, 21))
        self.pushButton_12.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_12.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_12.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_12.setText(u"")
        self.pushButton_12.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_12.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_12.setCheckable(False)
        self.pushButton_12.setAutoDefault(False)
        self.pushButton_12.setFlat(True)
        self.pushButton_13 = QPushButton(MainWindow)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setEnabled(True)
        self.pushButton_13.setGeometry(QRect(240, 50, 21, 21))
        self.pushButton_13.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_13.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_13.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_13.setAutoFillBackground(False)
        self.pushButton_13.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_13.setText(u"")
        self.pushButton_13.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_13.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_13.setCheckable(False)
        self.pushButton_13.setAutoDefault(False)
        self.pushButton_13.setFlat(True)
        self.pushButton_14 = QPushButton(MainWindow)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setEnabled(True)
        self.pushButton_14.setGeometry(QRect(307, 50, 21, 21))
        self.pushButton_14.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_14.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_14.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_14.setAutoFillBackground(False)
        self.pushButton_14.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_14.setText(u"")
        self.pushButton_14.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_14.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_14.setCheckable(False)
        self.pushButton_14.setAutoDefault(False)
        self.pushButton_14.setFlat(True)
        self.pushButton_15 = QPushButton(MainWindow)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setEnabled(True)
        self.pushButton_15.setGeometry(QRect(100, 350, 21, 21))
        self.pushButton_15.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_15.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_15.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_15.setAutoFillBackground(False)
        self.pushButton_15.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_15.setText(u"")
        self.pushButton_15.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_15.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_15.setCheckable(False)
        self.pushButton_15.setAutoDefault(False)
        self.pushButton_15.setFlat(True)
        self.pushButton_16 = QPushButton(MainWindow)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setEnabled(True)
        self.pushButton_16.setGeometry(QRect(237, 350, 21, 21))
        self.pushButton_16.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_16.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_16.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_16.setAutoFillBackground(False)
        self.pushButton_16.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_16.setText(u"")
        self.pushButton_16.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_16.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_16.setCheckable(False)
        self.pushButton_16.setAutoDefault(False)
        self.pushButton_16.setFlat(True)
        self.pushButton_17 = QPushButton(MainWindow)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setEnabled(True)
        self.pushButton_17.setGeometry(QRect(310, 350, 21, 21))
        self.pushButton_17.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_17.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_17.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_17.setAutoFillBackground(False)
        self.pushButton_17.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_17.setText(u"")
        self.pushButton_17.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_17.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_17.setCheckable(False)
        self.pushButton_17.setAutoDefault(False)
        self.pushButton_17.setFlat(True)
        self.pushButton_18 = QPushButton(MainWindow)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setEnabled(True)
        self.pushButton_18.setGeometry(QRect(250, 270, 21, 21))
        self.pushButton_18.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_18.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_18.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_18.setAutoFillBackground(False)
        self.pushButton_18.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_18.setText(u"")
        self.pushButton_18.setIcon(icon1)
#if QT_CONFIG(shortcut)
        self.pushButton_18.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_18.setCheckable(False)
        self.pushButton_18.setAutoDefault(False)
        self.pushButton_18.setFlat(True)
        self.pushButton_20 = QPushButton(MainWindow)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setEnabled(True)
        self.pushButton_20.setGeometry(QRect(239, 10, 21, 21))
        self.pushButton_20.setFont(font3)
#if QT_CONFIG(tooltip)
        self.pushButton_20.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.pushButton_20.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_20.setAutoFillBackground(False)
        self.pushButton_20.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_20.setText(u"")
        icon2 = QIcon()
        icon2.addFile(u":/icon_green/icon_Green.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_20.setIcon(icon2)
        self.pushButton_20.setIconSize(QSize(20, 16))
#if QT_CONFIG(shortcut)
        self.pushButton_20.setShortcut(u"")
#endif // QT_CONFIG(shortcut)
        self.pushButton_20.setCheckable(False)
        self.pushButton_20.setAutoDefault(False)
        self.pushButton_20.setFlat(True)
        self.label_4.raise_()
        self.verticalSlider.raise_()
        self.horizontalSlider.raise_()
        self.label.raise_()
        self.verticalSlider_2.raise_()
        self.label_2.raise_()
        self.horizontalSlider_2.raise_()
        self.verticalSlider_3.raise_()
        self.label_3.raise_()
        self.horizontalSlider_3.raise_()
        self.verticalSlider_5.raise_()
        self.verticalSlider_4.raise_()
        self.verticalSlider_6.raise_()
        self.verticalSlider_7.raise_()
        self.verticalSlider_8.raise_()
        self.label_5.raise_()
        self.horizontalSlider_4.raise_()
        self.verticalSlider_9.raise_()
        self.label_6.raise_()
        self.horizontalSlider_5.raise_()
        self.horizontalSlider_6.raise_()
        self.label_7.raise_()
        self.verticalSlider_10.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.verticalSlider_12.raise_()
        self.horizontalSlider_7.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.pushButton_20.raise_()

        self.retranslateUi(MainWindow)

        self.pushButton.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(whatsthis)
        self.label.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label.setText(QCoreApplication.translate("MainWindow", u"BrowR", None))
        self.label_4.setText("")
#if QT_CONFIG(whatsthis)
        self.label_2.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Squash", None))
#if QT_CONFIG(whatsthis)
        self.label_3.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"BrowL", None))
#if QT_CONFIG(whatsthis)
        self.label_5.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Puffin and Puffout", None))
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Jaw", None))
#if QT_CONFIG(whatsthis)
        self.label_7.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Sad and Smile", None))
#if QT_CONFIG(whatsthis)
        self.label_8.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Eye R", None))
#if QT_CONFIG(whatsthis)
        self.label_9.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Eye L", None))
#if QT_CONFIG(whatsthis)
        self.label_10.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"E", None))
#if QT_CONFIG(whatsthis)
        self.label_11.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt;\">BrowR</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"U", None))
        self.pushButton.setText("")
    # retranslateUi

